CREATE DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO STUDENT (ID, NAME)
VALUES (101, "ADAM"), (102, "CASEY"), (103, "BOB");

CREATE TABLE COURSES(
	ID INT PRIMARY KEY,
    COURSE VARCHAR(50)
);

INSERT INTO COURSES ( ID, COURSE) 
VALUES (102, "KANNADA"), (105, "MATHEMATICS"), (103, "SCIENCE"), (107,"CS");

SELECT * FROM STUDENT;
SELECT * FROM COURSES;